### PR TITLE
Exclude /target/site/* from Sonar scan

### PR DESCRIPTION
**Pull request by liry**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by lukas-slovak** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-parent-merge-compliance-check/6/ : SUCCESS in 23s
- https://checklist.intgdc.com/job/compliance/job/gooddata-parent-fossa-scanning-zuul-el7/2/ : SUCCESS in 1m 01s (non-voting)

**Pull request merged**
