### PR TITLE
Simplify license headers & add Kotlin

### PR DESCRIPTION
**Pull request by liry**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by lukas-slovak** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-parent-merge-compliance-check/7/ : SUCCESS in 20s
- https://checklist.intgdc.com/job/compliance/job/gooddata-parent-fossa-scanning-zuul-el7/3/ : SUCCESS in 1m 29s (non-voting)

**Pull request merged**
